<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Library-System/library_system.csproj" />
    <None Include="../database/schema.sql" Link="schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
