BEGIN;

CREATE TABLE IF NOT EXISTS Librarian (
    LibrarianID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name text NOT NULL CHECK (btrim(Name) <> ''),
    Username text NOT NULL UNIQUE CHECK (btrim(Username) <> ''),
    Password text NOT NULL
);

CREATE TABLE IF NOT EXISTS Category (
    CategoryID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName text NOT NULL UNIQUE CHECK (btrim(CategoryName) <> ''),
    Description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Book (
    BookID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ISBN text NOT NULL UNIQUE CHECK (btrim(ISBN) <> ''),
    Title text NOT NULL CHECK (btrim(Title) <> ''),
    Author text NOT NULL CHECK (btrim(Author) <> ''),
    CategoryID integer NOT NULL REFERENCES Category(CategoryID) ON DELETE RESTRICT,
    Publisher text NOT NULL DEFAULT '',
    PublishYear integer NOT NULL CHECK (PublishYear BETWEEN 1 AND 9999),
    Quantity integer NOT NULL CHECK (Quantity >= 0),
    AvailableQuantity integer NOT NULL CHECK (AvailableQuantity BETWEEN 0 AND Quantity)
);

CREATE TABLE IF NOT EXISTS Member (
    MemberID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name text NOT NULL CHECK (btrim(Name) <> ''),
    Gender text NOT NULL DEFAULT '',
    Phone text NOT NULL DEFAULT '',
    Email text NOT NULL DEFAULT '',
    Address text NOT NULL DEFAULT '',
    RegisterDate date NOT NULL DEFAULT CURRENT_DATE,
    Status text NOT NULL DEFAULT 'Active' CHECK (Status IN ('Active', 'Inactive'))
);

CREATE TABLE IF NOT EXISTS Borrow (
    BorrowID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MemberID integer NOT NULL REFERENCES Member(MemberID) ON DELETE RESTRICT,
    LibrarianID integer NOT NULL REFERENCES Librarian(LibrarianID) ON DELETE RESTRICT,
    BorrowDate date NOT NULL,
    DueDate date NOT NULL CHECK (DueDate >= BorrowDate),
    Status text NOT NULL DEFAULT 'Borrowed' CHECK (Status IN ('Borrowed', 'Returned'))
);

CREATE TABLE IF NOT EXISTS BorrowDetail (
    BorrowDetailID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BorrowID integer NOT NULL REFERENCES Borrow(BorrowID) ON DELETE RESTRICT,
    BookID integer NOT NULL REFERENCES Book(BookID) ON DELETE RESTRICT,
    ReturnDate date,
    Fine numeric(12,2) NOT NULL DEFAULT 0 CHECK (Fine >= 0),
    Status text NOT NULL DEFAULT 'Borrowed' CHECK (Status IN ('Borrowed', 'Returned')),
    UNIQUE (BorrowID, BookID),
    CHECK ((Status = 'Returned') = (ReturnDate IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS ix_book_category ON Book(CategoryID);
CREATE INDEX IF NOT EXISTS ix_borrow_member ON Borrow(MemberID);
CREATE INDEX IF NOT EXISTS ix_borrow_librarian ON Borrow(LibrarianID);
CREATE INDEX IF NOT EXISTS ix_borrow_dates ON Borrow(BorrowDate, DueDate);
CREATE INDEX IF NOT EXISTS ix_detail_book ON BorrowDetail(BookID);
CREATE INDEX IF NOT EXISTS ix_detail_outstanding ON BorrowDetail(BorrowID) WHERE ReturnDate IS NULL;

COMMIT;
